-- V1 — Creación de tablas: feriados y reglas_restriccion

CREATE TABLE feriados (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha      DATE         NOT NULL UNIQUE,
    nombre     VARCHAR(150) NOT NULL,
    tipo       VARCHAR(50)  NOT NULL,
    activo     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reglas_restriccion (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dia_semana       VARCHAR(20)  NOT NULL,
    digitos          VARCHAR(10)  NOT NULL,
    franja_inicio_1  TIME         NOT NULL,
    franja_fin_1     TIME         NOT NULL,
    franja_inicio_2  TIME         NOT NULL,
    franja_fin_2     TIME         NOT NULL,
    vigente_desde    DATE         NOT NULL,
    vigente_hasta    DATE,
    activo           BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_feriados_fecha      ON feriados (fecha);
CREATE INDEX idx_regla_dia_vigencia  ON reglas_restriccion (dia_semana, vigente_desde, vigente_hasta);
